name: beatx_cli
description: An opinionated framework for building Flutter apps. `beatx_rx`, `beatx_annotations`, `go_router`, `beatx_router`.
version: 0.1.1
homepage: https://github.com/beatly-dev/beatx
issue_tracker: https://github.com/beatly-dev/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  args: ^2.3.1
  collection: ^1.16.0
  path: ^1.8.2
  go_router_builder: ^1.0.10
  json_annotation: ^4.6.0
  source_gen: ^1.2.2
  dart_style: ^2.2.3

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
  beatx_annotations: ^0.1.1
executables:
  beatx:
